services:
  db:
    image: postgres:18
    container_name: url-shortener-postgres-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - dokploy-network
    restart: unless-stopped

  backend:
    image: abelharo2/url-shortener-backend:latest
    pull_policy: always
    container_name: url-shortener-backend
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - JWT_SECRET=${JWT_SECRET}
      - PRODUCTION=true
      - GIN_MODE=release
      - TRUSTED_PROXIES=0.0.0.0/0
    expose:
      - 8080
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`api-url-shortener.abelharo.me`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=letsencrypt
      - traefik.http.services.backend.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=true
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped

  frontend:
    image: abelharo2/url-shortener-frontend:latest
    pull_policy: always
    container_name: url-shortener-frontend
    expose:
      - 80
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`url-shortener.abelharo.me`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=letsencrypt
      - traefik.http.services.frontend.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
    depends_on:
      - backend
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30 --label-enable

networks:
  dokploy-network:
    external: true

volumes:
  postgres_data:
