services:
  db:
    image: postgres:18
    container_name: url-shortener-postgres-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - dokploy-network
    restart: unless-stopped

  backend:
    image: ${DOCKERHUB_USERNAME}/url-shortener-backend:${TAG:-latest}
    container_name: url-shortener-backend
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

    expose:
      - 8080
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`api.url-shortener.abelharo.me`)
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.services.backend.loadbalancer.server.port=8080
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped

  frontend:
    image: ${DOCKERHUB_USERNAME}/url-shortener-frontend:${TAG:-latest}
    container_name: url-shortener-frontend
    expose:
      - 80
    networks:
      - dokploy-network
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.frontend.rule=Host(`url-shortener.abelharo.me`)
        - traefik.http.routers.frontend.entrypoints=web
        - traefik.http.services.frontend.loadbalancer.server.port=80
    depends_on:
      - backend
    restart: unless-stopped

networks:
  dokploy-network:
    external: true

volumes:
  postgres_data:
