services:
  db:
    image: postgres:18
    container_name: url-shortener-postgres-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s

  backend:
    image: ${DOCKERHUB_USERNAME}/url-shortener-backend:${TAG:-latest}
    container_name: url-shortener-backend
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=8080
    networks:
      - app-network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`api.url-shortener.abelharo.me`)"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls.certresolver=le"
        - "traefik.http.services.backend.loadbalancer.server.port=8080"
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped

  frontend:
    image: ${DOCKERHUB_USERNAME}/url-shortener-frontend:${TAG:-latest}
    container_name: url-shortener-frontend
    networks:
      - app-network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`url-shortener.abelharo.me`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls.certresolver=le"
        - "traefik.http.services.frontend.loadbalancer.server.port=80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
