
services:
  db:
    image : postgres:18
    restart: always
    environment:
      POSTGRES_PASSWORD: gorm
      POSTGRES_USER: gorm
      POSTGRES_DB: gorm
    volumes:
      - pgdata:/var/lib/postgresql/
    ports:
      - "5432:5432"



volumes:
  pgdata:
