/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * URL Shortener API
 * API for shortening URLs
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DomainURL,
  DtosAuthResponse,
  DtosCreateShortenRequest,
  DtosErrorResponse,
  DtosLoginRequest,
  DtosRefreshTokenRequest,
  DtosRegisterRequest,
  DtosSearchByOriginalURLRequest,
  DtosSessionResponse,
  DtosTokenResponse,
  DtosURLResponse,
  HealthResponse
} from './model';

import { authFetch } from './fetcher';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Redirects a shortened URL to its original URL
 * @summary Redirect to original URL
 */
export type getRedirectResponse301 = {
  data: void
  status: 301
}

;
export type getRedirectResponseError = (getRedirectResponse301) & {
  headers: Headers;
};

export type getRedirectResponse = (getRedirectResponseError)

export const getGetRedirectUrl = (shortURL: string,) => {




  return `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/${shortURL}`
}

export const getRedirect = async (shortURL: string, options?: RequestInit): Promise<getRedirectResponse> => {

  return authFetch<getRedirectResponse>(getGetRedirectUrl(shortURL),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetRedirectQueryKey = (shortURL: string,) => {
    return [
    `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/${shortURL}`
    ] as const;
    }


export const getGetRedirectQueryOptions = <TData = Awaited<ReturnType<typeof getRedirect>>, TError = void>(shortURL: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRedirect>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRedirectQueryKey(shortURL);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRedirect>>> = ({ signal }) => getRedirect(shortURL, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(shortURL), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRedirect>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRedirectQueryResult = NonNullable<Awaited<ReturnType<typeof getRedirect>>>
export type GetRedirectQueryError = void


export function useGetRedirect<TData = Awaited<ReturnType<typeof getRedirect>>, TError = void>(
 shortURL: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRedirect>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRedirect>>,
          TError,
          Awaited<ReturnType<typeof getRedirect>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRedirect<TData = Awaited<ReturnType<typeof getRedirect>>, TError = void>(
 shortURL: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRedirect>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRedirect>>,
          TError,
          Awaited<ReturnType<typeof getRedirect>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRedirect<TData = Awaited<ReturnType<typeof getRedirect>>, TError = void>(
 shortURL: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRedirect>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Redirect to original URL
 */

export function useGetRedirect<TData = Awaited<ReturnType<typeof getRedirect>>, TError = void>(
 shortURL: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRedirect>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRedirectQueryOptions(shortURL,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * Create a new anonymous account with a random name
 * @summary Register anonymous user
 */
export type postAuthAnonymousRegisterResponse201 = {
  data: DtosAuthResponse
  status: 201
}

export type postAuthAnonymousRegisterResponse500 = {
  data: DtosErrorResponse
  status: 500
}

export type postAuthAnonymousRegisterResponseSuccess = (postAuthAnonymousRegisterResponse201) & {
  headers: Headers;
};
export type postAuthAnonymousRegisterResponseError = (postAuthAnonymousRegisterResponse500) & {
  headers: Headers;
};

export type postAuthAnonymousRegisterResponse = (postAuthAnonymousRegisterResponseSuccess | postAuthAnonymousRegisterResponseError)

export const getPostAuthAnonymousRegisterUrl = () => {




  return `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/auth/anonymous`
}

export const postAuthAnonymousRegister = async ( options?: RequestInit): Promise<postAuthAnonymousRegisterResponse> => {

  return authFetch<postAuthAnonymousRegisterResponse>(getPostAuthAnonymousRegisterUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostAuthAnonymousRegisterMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthAnonymousRegister>>, TError,void, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthAnonymousRegister>>, TError,void, TContext> => {

const mutationKey = ['postAuthAnonymousRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthAnonymousRegister>>, void> = () => {


          return  postAuthAnonymousRegister(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthAnonymousRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthAnonymousRegister>>>

    export type PostAuthAnonymousRegisterMutationError = DtosErrorResponse

    /**
 * @summary Register anonymous user
 */
export const usePostAuthAnonymousRegister = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthAnonymousRegister>>, TError,void, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthAnonymousRegister>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostAuthAnonymousRegisterMutationOptions(options), queryClient);
    }

/**
 * Authenticate with email and password, returns access and refresh tokens
 * @summary Login user
 */
export type postAuthLoginResponse200 = {
  data: DtosAuthResponse
  status: 200
}

export type postAuthLoginResponse400 = {
  data: DtosErrorResponse
  status: 400
}

export type postAuthLoginResponse401 = {
  data: DtosErrorResponse
  status: 401
}

export type postAuthLoginResponseSuccess = (postAuthLoginResponse200) & {
  headers: Headers;
};
export type postAuthLoginResponseError = (postAuthLoginResponse400 | postAuthLoginResponse401) & {
  headers: Headers;
};

export type postAuthLoginResponse = (postAuthLoginResponseSuccess | postAuthLoginResponseError)

export const getPostAuthLoginUrl = () => {




  return `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/auth/login`
}

export const postAuthLogin = async (dtosLoginRequest: DtosLoginRequest, options?: RequestInit): Promise<postAuthLoginResponse> => {

  return authFetch<postAuthLoginResponse>(getPostAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtosLoginRequest,)
  }
);}




export const getPostAuthLoginMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: DtosLoginRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: DtosLoginRequest}, TContext> => {

const mutationKey = ['postAuthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogin>>, {data: DtosLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>
    export type PostAuthLoginMutationBody = DtosLoginRequest
    export type PostAuthLoginMutationError = DtosErrorResponse

    /**
 * @summary Login user
 */
export const usePostAuthLogin = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: DtosLoginRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogin>>,
        TError,
        {data: DtosLoginRequest},
        TContext
      > => {
      return useMutation(getPostAuthLoginMutationOptions(options), queryClient);
    }

/**
 * Invalidate all refresh tokens for the authenticated user
 * @summary Logout user
 */
export type postAuthLogoutResponse204 = {
  data: void
  status: 204
}

export type postAuthLogoutResponse401 = {
  data: DtosErrorResponse
  status: 401
}

export type postAuthLogoutResponseSuccess = (postAuthLogoutResponse204) & {
  headers: Headers;
};
export type postAuthLogoutResponseError = (postAuthLogoutResponse401) & {
  headers: Headers;
};

export type postAuthLogoutResponse = (postAuthLogoutResponseSuccess | postAuthLogoutResponseError)

export const getPostAuthLogoutUrl = () => {




  return `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/auth/logout`
}

export const postAuthLogout = async ( options?: RequestInit): Promise<postAuthLogoutResponse> => {

  return authFetch<postAuthLogoutResponse>(getPostAuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostAuthLogoutMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext> => {

const mutationKey = ['postAuthLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogout>>, void> = () => {


          return  postAuthLogout(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogout>>>

    export type PostAuthLogoutMutationError = DtosErrorResponse

    /**
 * @summary Logout user
 */
export const usePostAuthLogout = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostAuthLogoutMutationOptions(options), queryClient);
    }

/**
 * Use refresh token to get a new access token and refresh token
 * @summary Refresh access token
 */
export type postAuthRefreshResponse200 = {
  data: DtosTokenResponse
  status: 200
}

export type postAuthRefreshResponse400 = {
  data: DtosErrorResponse
  status: 400
}

export type postAuthRefreshResponse401 = {
  data: DtosErrorResponse
  status: 401
}

export type postAuthRefreshResponseSuccess = (postAuthRefreshResponse200) & {
  headers: Headers;
};
export type postAuthRefreshResponseError = (postAuthRefreshResponse400 | postAuthRefreshResponse401) & {
  headers: Headers;
};

export type postAuthRefreshResponse = (postAuthRefreshResponseSuccess | postAuthRefreshResponseError)

export const getPostAuthRefreshUrl = () => {




  return `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/auth/refresh`
}

export const postAuthRefresh = async (dtosRefreshTokenRequest: DtosRefreshTokenRequest, options?: RequestInit): Promise<postAuthRefreshResponse> => {

  return authFetch<postAuthRefreshResponse>(getPostAuthRefreshUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtosRefreshTokenRequest,)
  }
);}




export const getPostAuthRefreshMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,{data: DtosRefreshTokenRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,{data: DtosRefreshTokenRequest}, TContext> => {

const mutationKey = ['postAuthRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRefresh>>, {data: DtosRefreshTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthRefresh(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRefresh>>>
    export type PostAuthRefreshMutationBody = DtosRefreshTokenRequest
    export type PostAuthRefreshMutationError = DtosErrorResponse

    /**
 * @summary Refresh access token
 */
export const usePostAuthRefresh = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,{data: DtosRefreshTokenRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthRefresh>>,
        TError,
        {data: DtosRefreshTokenRequest},
        TContext
      > => {
      return useMutation(getPostAuthRefreshMutationOptions(options), queryClient);
    }

/**
 * Create a new user account with email and password
 * @summary Register a new user
 */
export type postAuthRegisterResponse201 = {
  data: DtosAuthResponse
  status: 201
}

export type postAuthRegisterResponse400 = {
  data: DtosErrorResponse
  status: 400
}

export type postAuthRegisterResponse409 = {
  data: DtosErrorResponse
  status: 409
}

export type postAuthRegisterResponseSuccess = (postAuthRegisterResponse201) & {
  headers: Headers;
};
export type postAuthRegisterResponseError = (postAuthRegisterResponse400 | postAuthRegisterResponse409) & {
  headers: Headers;
};

export type postAuthRegisterResponse = (postAuthRegisterResponseSuccess | postAuthRegisterResponseError)

export const getPostAuthRegisterUrl = () => {




  return `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/auth/register`
}

export const postAuthRegister = async (dtosRegisterRequest: DtosRegisterRequest, options?: RequestInit): Promise<postAuthRegisterResponse> => {

  return authFetch<postAuthRegisterResponse>(getPostAuthRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtosRegisterRequest,)
  }
);}




export const getPostAuthRegisterMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: DtosRegisterRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: DtosRegisterRequest}, TContext> => {

const mutationKey = ['postAuthRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRegister>>, {data: DtosRegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthRegister(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRegister>>>
    export type PostAuthRegisterMutationBody = DtosRegisterRequest
    export type PostAuthRegisterMutationError = DtosErrorResponse

    /**
 * @summary Register a new user
 */
export const usePostAuthRegister = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: DtosRegisterRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthRegister>>,
        TError,
        {data: DtosRegisterRequest},
        TContext
      > => {
      return useMutation(getPostAuthRegisterMutationOptions(options), queryClient);
    }

/**
 * Returns the current authenticated user
 * @summary Current session
 */
export type getAuthSessionResponse200 = {
  data: DtosSessionResponse
  status: 200
}

export type getAuthSessionResponse401 = {
  data: DtosErrorResponse
  status: 401
}

export type getAuthSessionResponseSuccess = (getAuthSessionResponse200) & {
  headers: Headers;
};
export type getAuthSessionResponseError = (getAuthSessionResponse401) & {
  headers: Headers;
};

export type getAuthSessionResponse = (getAuthSessionResponseSuccess | getAuthSessionResponseError)

export const getGetAuthSessionUrl = () => {




  return `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/auth/session`
}

export const getAuthSession = async ( options?: RequestInit): Promise<getAuthSessionResponse> => {

  return authFetch<getAuthSessionResponse>(getGetAuthSessionUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthSessionQueryKey = () => {
    return [
    `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/auth/session`
    ] as const;
    }


export const getGetAuthSessionQueryOptions = <TData = Awaited<ReturnType<typeof getAuthSession>>, TError = DtosErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthSession>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthSessionQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthSession>>> = ({ signal }) => getAuthSession({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuthSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthSession>>>
export type GetAuthSessionQueryError = DtosErrorResponse


export function useGetAuthSession<TData = Awaited<ReturnType<typeof getAuthSession>>, TError = DtosErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthSession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthSession>>,
          TError,
          Awaited<ReturnType<typeof getAuthSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthSession<TData = Awaited<ReturnType<typeof getAuthSession>>, TError = DtosErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthSession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthSession>>,
          TError,
          Awaited<ReturnType<typeof getAuthSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthSession<TData = Awaited<ReturnType<typeof getAuthSession>>, TError = DtosErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthSession>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Current session
 */

export function useGetAuthSession<TData = Awaited<ReturnType<typeof getAuthSession>>, TError = DtosErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthSession>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuthSessionQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * Returns the health status of the API
 * @summary Health check
 */
export type getHealthResponse200 = {
  data: HealthResponse
  status: 200
}

export type getHealthResponseSuccess = (getHealthResponse200) & {
  headers: Headers;
};
;

export type getHealthResponse = (getHealthResponseSuccess)

export const getGetHealthUrl = () => {




  return `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/health`
}

export const getHealth = async ( options?: RequestInit): Promise<getHealthResponse> => {

  return authFetch<getHealthResponse>(getGetHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetHealthQueryKey = () => {
    return [
    `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/health`
    ] as const;
    }


export const getGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({ signal }) => getHealth({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = unknown


export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health check
 */

export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * Create a shortened URL from a long URL
 * @summary Shorten a URL
 */
export type postShortenURLResponse201 = {
  data: DtosURLResponse
  status: 201
}

export type postShortenURLResponse400 = {
  data: DtosErrorResponse
  status: 400
}

export type postShortenURLResponseSuccess = (postShortenURLResponse201) & {
  headers: Headers;
};
export type postShortenURLResponseError = (postShortenURLResponse400) & {
  headers: Headers;
};

export type postShortenURLResponse = (postShortenURLResponseSuccess | postShortenURLResponseError)

export const getPostShortenURLUrl = () => {




  return `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/shorten`
}

export const postShortenURL = async (dtosCreateShortenRequest: DtosCreateShortenRequest, options?: RequestInit): Promise<postShortenURLResponse> => {

  return authFetch<postShortenURLResponse>(getPostShortenURLUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtosCreateShortenRequest,)
  }
);}




export const getPostShortenURLMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postShortenURL>>, TError,{data: DtosCreateShortenRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postShortenURL>>, TError,{data: DtosCreateShortenRequest}, TContext> => {

const mutationKey = ['postShortenURL'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postShortenURL>>, {data: DtosCreateShortenRequest}> = (props) => {
          const {data} = props ?? {};

          return  postShortenURL(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostShortenURLMutationResult = NonNullable<Awaited<ReturnType<typeof postShortenURL>>>
    export type PostShortenURLMutationBody = DtosCreateShortenRequest
    export type PostShortenURLMutationError = DtosErrorResponse

    /**
 * @summary Shorten a URL
 */
export const usePostShortenURL = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postShortenURL>>, TError,{data: DtosCreateShortenRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postShortenURL>>,
        TError,
        {data: DtosCreateShortenRequest},
        TContext
      > => {
      return useMutation(getPostShortenURLMutationOptions(options), queryClient);
    }

/**
 * Delete a URL by its ID
 * @summary Delete URL
 */
export type deleteURLByIDResponse204 = {
  data: void
  status: 204
}

export type deleteURLByIDResponse404 = {
  data: DtosErrorResponse
  status: 404
}

export type deleteURLByIDResponseSuccess = (deleteURLByIDResponse204) & {
  headers: Headers;
};
export type deleteURLByIDResponseError = (deleteURLByIDResponse404) & {
  headers: Headers;
};

export type deleteURLByIDResponse = (deleteURLByIDResponseSuccess | deleteURLByIDResponseError)

export const getDeleteURLByIDUrl = (id: string,) => {




  return `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/urls/${id}`
}

export const deleteURLByID = async (id: string, options?: RequestInit): Promise<deleteURLByIDResponse> => {

  return authFetch<deleteURLByIDResponse>(getDeleteURLByIDUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteURLByIDMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteURLByID>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteURLByID>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteURLByID'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteURLByID>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteURLByID(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteURLByIDMutationResult = NonNullable<Awaited<ReturnType<typeof deleteURLByID>>>

    export type DeleteURLByIDMutationError = DtosErrorResponse

    /**
 * @summary Delete URL
 */
export const useDeleteURLByID = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteURLByID>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteURLByID>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteURLByIDMutationOptions(options), queryClient);
    }

/**
 * Retrieve a URL by its ID
 * @summary Get URL by ID
 */
export type getURLByIDResponse200 = {
  data: DomainURL
  status: 200
}

export type getURLByIDResponse404 = {
  data: DtosErrorResponse
  status: 404
}

export type getURLByIDResponseSuccess = (getURLByIDResponse200) & {
  headers: Headers;
};
export type getURLByIDResponseError = (getURLByIDResponse404) & {
  headers: Headers;
};

export type getURLByIDResponse = (getURLByIDResponseSuccess | getURLByIDResponseError)

export const getGetURLByIDUrl = (id: string,) => {




  return `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/urls/${id}`
}

export const getURLByID = async (id: string, options?: RequestInit): Promise<getURLByIDResponse> => {

  return authFetch<getURLByIDResponse>(getGetURLByIDUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetURLByIDQueryKey = (id: string,) => {
    return [
    `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/urls/${id}`
    ] as const;
    }


export const getGetURLByIDQueryOptions = <TData = Awaited<ReturnType<typeof getURLByID>>, TError = DtosErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByID>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetURLByIDQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getURLByID>>> = ({ signal }) => getURLByID(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getURLByID>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetURLByIDQueryResult = NonNullable<Awaited<ReturnType<typeof getURLByID>>>
export type GetURLByIDQueryError = DtosErrorResponse


export function useGetURLByID<TData = Awaited<ReturnType<typeof getURLByID>>, TError = DtosErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByID>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getURLByID>>,
          TError,
          Awaited<ReturnType<typeof getURLByID>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetURLByID<TData = Awaited<ReturnType<typeof getURLByID>>, TError = DtosErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByID>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getURLByID>>,
          TError,
          Awaited<ReturnType<typeof getURLByID>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetURLByID<TData = Awaited<ReturnType<typeof getURLByID>>, TError = DtosErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByID>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get URL by ID
 */

export function useGetURLByID<TData = Awaited<ReturnType<typeof getURLByID>>, TError = DtosErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByID>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetURLByIDQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * Find a shortened URL by its original URL
 * @summary Search URL by original URL
 */
export type postURLsSearchResponse200 = {
  data: DomainURL
  status: 200
}

export type postURLsSearchResponse404 = {
  data: DtosErrorResponse
  status: 404
}

export type postURLsSearchResponseSuccess = (postURLsSearchResponse200) & {
  headers: Headers;
};
export type postURLsSearchResponseError = (postURLsSearchResponse404) & {
  headers: Headers;
};

export type postURLsSearchResponse = (postURLsSearchResponseSuccess | postURLsSearchResponseError)

export const getPostURLsSearchUrl = () => {




  return `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/urls/search`
}

export const postURLsSearch = async (dtosSearchByOriginalURLRequest: DtosSearchByOriginalURLRequest, options?: RequestInit): Promise<postURLsSearchResponse> => {

  return authFetch<postURLsSearchResponse>(getPostURLsSearchUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtosSearchByOriginalURLRequest,)
  }
);}




export const getPostURLsSearchMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postURLsSearch>>, TError,{data: DtosSearchByOriginalURLRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postURLsSearch>>, TError,{data: DtosSearchByOriginalURLRequest}, TContext> => {

const mutationKey = ['postURLsSearch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postURLsSearch>>, {data: DtosSearchByOriginalURLRequest}> = (props) => {
          const {data} = props ?? {};

          return  postURLsSearch(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostURLsSearchMutationResult = NonNullable<Awaited<ReturnType<typeof postURLsSearch>>>
    export type PostURLsSearchMutationBody = DtosSearchByOriginalURLRequest
    export type PostURLsSearchMutationError = DtosErrorResponse

    /**
 * @summary Search URL by original URL
 */
export const usePostURLsSearch = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postURLsSearch>>, TError,{data: DtosSearchByOriginalURLRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postURLsSearch>>,
        TError,
        {data: DtosSearchByOriginalURLRequest},
        TContext
      > => {
      return useMutation(getPostURLsSearchMutationOptions(options), queryClient);
    }

/**
 * Retrieve a URL by its short code
 * @summary Get URL by short code
 */
export type getURLByShortCodeResponse200 = {
  data: DomainURL
  status: 200
}

export type getURLByShortCodeResponse404 = {
  data: DtosErrorResponse
  status: 404
}

export type getURLByShortCodeResponseSuccess = (getURLByShortCodeResponse200) & {
  headers: Headers;
};
export type getURLByShortCodeResponseError = (getURLByShortCodeResponse404) & {
  headers: Headers;
};

export type getURLByShortCodeResponse = (getURLByShortCodeResponseSuccess | getURLByShortCodeResponseError)

export const getGetURLByShortCodeUrl = (shortCode: string,) => {




  return `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/urls/short/${shortCode}`
}

export const getURLByShortCode = async (shortCode: string, options?: RequestInit): Promise<getURLByShortCodeResponse> => {

  return authFetch<getURLByShortCodeResponse>(getGetURLByShortCodeUrl(shortCode),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetURLByShortCodeQueryKey = (shortCode: string,) => {
    return [
    `${import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080"}/urls/short/${shortCode}`
    ] as const;
    }


export const getGetURLByShortCodeQueryOptions = <TData = Awaited<ReturnType<typeof getURLByShortCode>>, TError = DtosErrorResponse>(shortCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByShortCode>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetURLByShortCodeQueryKey(shortCode);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getURLByShortCode>>> = ({ signal }) => getURLByShortCode(shortCode, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(shortCode), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getURLByShortCode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetURLByShortCodeQueryResult = NonNullable<Awaited<ReturnType<typeof getURLByShortCode>>>
export type GetURLByShortCodeQueryError = DtosErrorResponse


export function useGetURLByShortCode<TData = Awaited<ReturnType<typeof getURLByShortCode>>, TError = DtosErrorResponse>(
 shortCode: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByShortCode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getURLByShortCode>>,
          TError,
          Awaited<ReturnType<typeof getURLByShortCode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetURLByShortCode<TData = Awaited<ReturnType<typeof getURLByShortCode>>, TError = DtosErrorResponse>(
 shortCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByShortCode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getURLByShortCode>>,
          TError,
          Awaited<ReturnType<typeof getURLByShortCode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetURLByShortCode<TData = Awaited<ReturnType<typeof getURLByShortCode>>, TError = DtosErrorResponse>(
 shortCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByShortCode>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get URL by short code
 */

export function useGetURLByShortCode<TData = Awaited<ReturnType<typeof getURLByShortCode>>, TError = DtosErrorResponse>(
 shortCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByShortCode>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetURLByShortCodeQueryOptions(shortCode,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
