/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * URL Shortener API
 * API for shortening URLs
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DomainURL,
  DtosAuthResponse,
  DtosCreateShortenRequest,
  DtosErrorResponse,
  DtosLoginRequest,
  DtosRefreshTokenRequest,
  DtosRegisterRequest,
  DtosResolveShortURLRequest,
  DtosResolveShortURLResponse,
  DtosSearchByOriginalURLRequest,
  DtosSessionResponse,
  DtosTokenResponse,
  DtosURLResponse,
  DtosURLStatisticsResponse,
  DtosUpdateURLRequest,
  HealthResponse
} from './model';

import { authFetch } from './fetcher';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Redirects a shortened URL to its original URL
 * @summary Redirect to original URL
 */
export const getRedirect = (
    shortURL: string,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<unknown>(
      {url: `/${shortURL}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetRedirectQueryKey = (shortURL?: string,) => {
    return [
    `/${shortURL}`
    ] as const;
    }

    
export const getGetRedirectQueryOptions = <TData = Awaited<ReturnType<typeof getRedirect>>, TError = void>(shortURL: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRedirect>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRedirectQueryKey(shortURL);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRedirect>>> = ({ signal }) => getRedirect(shortURL, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(shortURL), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRedirect>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRedirectQueryResult = NonNullable<Awaited<ReturnType<typeof getRedirect>>>
export type GetRedirectQueryError = void


export function useGetRedirect<TData = Awaited<ReturnType<typeof getRedirect>>, TError = void>(
 shortURL: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRedirect>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRedirect>>,
          TError,
          Awaited<ReturnType<typeof getRedirect>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRedirect<TData = Awaited<ReturnType<typeof getRedirect>>, TError = void>(
 shortURL: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRedirect>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRedirect>>,
          TError,
          Awaited<ReturnType<typeof getRedirect>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRedirect<TData = Awaited<ReturnType<typeof getRedirect>>, TError = void>(
 shortURL: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRedirect>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Redirect to original URL
 */

export function useGetRedirect<TData = Awaited<ReturnType<typeof getRedirect>>, TError = void>(
 shortURL: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRedirect>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRedirectQueryOptions(shortURL,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Create a new anonymous account with a random name
 * @summary Register anonymous user
 */
export const postAuthAnonymousRegister = (
    
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<DtosAuthResponse>(
      {url: `/auth/anonymous`, method: 'POST', signal
    },
      options);
    }
  


export const getPostAuthAnonymousRegisterMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthAnonymousRegister>>, TError,void, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthAnonymousRegister>>, TError,void, TContext> => {

const mutationKey = ['postAuthAnonymousRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthAnonymousRegister>>, void> = () => {
          

          return  postAuthAnonymousRegister(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthAnonymousRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthAnonymousRegister>>>
    
    export type PostAuthAnonymousRegisterMutationError = DtosErrorResponse

    /**
 * @summary Register anonymous user
 */
export const usePostAuthAnonymousRegister = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthAnonymousRegister>>, TError,void, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthAnonymousRegister>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostAuthAnonymousRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Authenticate with email and password, returns access and refresh tokens
 * @summary Login user
 */
export const postAuthLogin = (
    dtosLoginRequest: DtosLoginRequest,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<DtosAuthResponse>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtosLoginRequest, signal
    },
      options);
    }
  


export const getPostAuthLoginMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: DtosLoginRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: DtosLoginRequest}, TContext> => {

const mutationKey = ['postAuthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogin>>, {data: DtosLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>
    export type PostAuthLoginMutationBody = DtosLoginRequest
    export type PostAuthLoginMutationError = DtosErrorResponse

    /**
 * @summary Login user
 */
export const usePostAuthLogin = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: DtosLoginRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogin>>,
        TError,
        {data: DtosLoginRequest},
        TContext
      > => {

      const mutationOptions = getPostAuthLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Invalidate all refresh tokens for the authenticated user
 * @summary Logout user
 */
export const postAuthLogout = (
    
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<void>(
      {url: `/auth/logout`, method: 'POST', signal
    },
      options);
    }
  


export const getPostAuthLogoutMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext> => {

const mutationKey = ['postAuthLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogout>>, void> = () => {
          

          return  postAuthLogout(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogout>>>
    
    export type PostAuthLogoutMutationError = DtosErrorResponse

    /**
 * @summary Logout user
 */
export const usePostAuthLogout = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostAuthLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Use refresh token to get a new access token and refresh token
 * @summary Refresh access token
 */
export const postAuthRefresh = (
    dtosRefreshTokenRequest: DtosRefreshTokenRequest,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<DtosTokenResponse>(
      {url: `/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtosRefreshTokenRequest, signal
    },
      options);
    }
  


export const getPostAuthRefreshMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,{data: DtosRefreshTokenRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,{data: DtosRefreshTokenRequest}, TContext> => {

const mutationKey = ['postAuthRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRefresh>>, {data: DtosRefreshTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthRefresh(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRefresh>>>
    export type PostAuthRefreshMutationBody = DtosRefreshTokenRequest
    export type PostAuthRefreshMutationError = DtosErrorResponse

    /**
 * @summary Refresh access token
 */
export const usePostAuthRefresh = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,{data: DtosRefreshTokenRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthRefresh>>,
        TError,
        {data: DtosRefreshTokenRequest},
        TContext
      > => {

      const mutationOptions = getPostAuthRefreshMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Create a new user account with email and password
 * @summary Register a new user
 */
export const postAuthRegister = (
    dtosRegisterRequest: DtosRegisterRequest,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<DtosAuthResponse>(
      {url: `/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtosRegisterRequest, signal
    },
      options);
    }
  


export const getPostAuthRegisterMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: DtosRegisterRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: DtosRegisterRequest}, TContext> => {

const mutationKey = ['postAuthRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRegister>>, {data: DtosRegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthRegister(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRegister>>>
    export type PostAuthRegisterMutationBody = DtosRegisterRequest
    export type PostAuthRegisterMutationError = DtosErrorResponse

    /**
 * @summary Register a new user
 */
export const usePostAuthRegister = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: DtosRegisterRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthRegister>>,
        TError,
        {data: DtosRegisterRequest},
        TContext
      > => {

      const mutationOptions = getPostAuthRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Returns the current authenticated user
 * @summary Current session
 */
export const getAuthSession = (
    
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<DtosSessionResponse>(
      {url: `/auth/session`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAuthSessionQueryKey = () => {
    return [
    `/auth/session`
    ] as const;
    }

    
export const getGetAuthSessionQueryOptions = <TData = Awaited<ReturnType<typeof getAuthSession>>, TError = DtosErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthSession>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthSessionQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthSession>>> = ({ signal }) => getAuthSession(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuthSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthSession>>>
export type GetAuthSessionQueryError = DtosErrorResponse


export function useGetAuthSession<TData = Awaited<ReturnType<typeof getAuthSession>>, TError = DtosErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthSession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthSession>>,
          TError,
          Awaited<ReturnType<typeof getAuthSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthSession<TData = Awaited<ReturnType<typeof getAuthSession>>, TError = DtosErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthSession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthSession>>,
          TError,
          Awaited<ReturnType<typeof getAuthSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthSession<TData = Awaited<ReturnType<typeof getAuthSession>>, TError = DtosErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthSession>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Current session
 */

export function useGetAuthSession<TData = Awaited<ReturnType<typeof getAuthSession>>, TError = DtosErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthSession>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuthSessionQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Returns the health status of the API
 * @summary Health check
 */
export const getHealth = (
    
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<HealthResponse>(
      {url: `/health`, method: 'GET', signal
    },
      options);
    }
  



export const getGetHealthQueryKey = () => {
    return [
    `/health`
    ] as const;
    }

    
export const getGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({ signal }) => getHealth(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = unknown


export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health check
 */

export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Create a shortened URL from a long URL
 * @summary Shorten a URL
 */
export const postShortenURL = (
    dtosCreateShortenRequest: DtosCreateShortenRequest,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<DtosURLResponse>(
      {url: `/shorten`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtosCreateShortenRequest, signal
    },
      options);
    }
  


export const getPostShortenURLMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postShortenURL>>, TError,{data: DtosCreateShortenRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postShortenURL>>, TError,{data: DtosCreateShortenRequest}, TContext> => {

const mutationKey = ['postShortenURL'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postShortenURL>>, {data: DtosCreateShortenRequest}> = (props) => {
          const {data} = props ?? {};

          return  postShortenURL(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostShortenURLMutationResult = NonNullable<Awaited<ReturnType<typeof postShortenURL>>>
    export type PostShortenURLMutationBody = DtosCreateShortenRequest
    export type PostShortenURLMutationError = DtosErrorResponse

    /**
 * @summary Shorten a URL
 */
export const usePostShortenURL = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postShortenURL>>, TError,{data: DtosCreateShortenRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postShortenURL>>,
        TError,
        {data: DtosCreateShortenRequest},
        TContext
      > => {

      const mutationOptions = getPostShortenURLMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Retrieve all shortened URLs created by a specific user
 * @summary Get all URLs by user ID
 */
export const getURLsByUserID = (
    
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<DomainURL[]>(
      {url: `/urls`, method: 'GET', signal
    },
      options);
    }
  



export const getGetURLsByUserIDQueryKey = () => {
    return [
    `/urls`
    ] as const;
    }

    
export const getGetURLsByUserIDQueryOptions = <TData = Awaited<ReturnType<typeof getURLsByUserID>>, TError = DtosErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLsByUserID>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetURLsByUserIDQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getURLsByUserID>>> = ({ signal }) => getURLsByUserID(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getURLsByUserID>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetURLsByUserIDQueryResult = NonNullable<Awaited<ReturnType<typeof getURLsByUserID>>>
export type GetURLsByUserIDQueryError = DtosErrorResponse


export function useGetURLsByUserID<TData = Awaited<ReturnType<typeof getURLsByUserID>>, TError = DtosErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLsByUserID>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getURLsByUserID>>,
          TError,
          Awaited<ReturnType<typeof getURLsByUserID>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetURLsByUserID<TData = Awaited<ReturnType<typeof getURLsByUserID>>, TError = DtosErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLsByUserID>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getURLsByUserID>>,
          TError,
          Awaited<ReturnType<typeof getURLsByUserID>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetURLsByUserID<TData = Awaited<ReturnType<typeof getURLsByUserID>>, TError = DtosErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLsByUserID>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all URLs by user ID
 */

export function useGetURLsByUserID<TData = Awaited<ReturnType<typeof getURLsByUserID>>, TError = DtosErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLsByUserID>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetURLsByUserIDQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Delete a URL by its ID
 * @summary Delete URL
 */
export const deleteURLByID = (
    id: string,
 options?: SecondParameter<typeof authFetch>,) => {
      
      
      return authFetch<void>(
      {url: `/urls/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteURLByIDMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteURLByID>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteURLByID>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteURLByID'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteURLByID>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteURLByID(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteURLByIDMutationResult = NonNullable<Awaited<ReturnType<typeof deleteURLByID>>>
    
    export type DeleteURLByIDMutationError = DtosErrorResponse

    /**
 * @summary Delete URL
 */
export const useDeleteURLByID = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteURLByID>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteURLByID>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteURLByIDMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Retrieve a URL by its ID
 * @summary Get URL by ID
 */
export const getURLByID = (
    id: string,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<DomainURL>(
      {url: `/urls/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetURLByIDQueryKey = (id?: string,) => {
    return [
    `/urls/${id}`
    ] as const;
    }

    
export const getGetURLByIDQueryOptions = <TData = Awaited<ReturnType<typeof getURLByID>>, TError = DtosErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByID>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetURLByIDQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getURLByID>>> = ({ signal }) => getURLByID(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getURLByID>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetURLByIDQueryResult = NonNullable<Awaited<ReturnType<typeof getURLByID>>>
export type GetURLByIDQueryError = DtosErrorResponse


export function useGetURLByID<TData = Awaited<ReturnType<typeof getURLByID>>, TError = DtosErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByID>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getURLByID>>,
          TError,
          Awaited<ReturnType<typeof getURLByID>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetURLByID<TData = Awaited<ReturnType<typeof getURLByID>>, TError = DtosErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByID>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getURLByID>>,
          TError,
          Awaited<ReturnType<typeof getURLByID>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetURLByID<TData = Awaited<ReturnType<typeof getURLByID>>, TError = DtosErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByID>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get URL by ID
 */

export function useGetURLByID<TData = Awaited<ReturnType<typeof getURLByID>>, TError = DtosErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByID>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetURLByIDQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Change the original URL while preserving the short code
 * @summary Update URL destination
 */
export const updateURLByID = (
    id: string,
    dtosUpdateURLRequest: DtosUpdateURLRequest,
 options?: SecondParameter<typeof authFetch>,) => {
      
      
      return authFetch<DtosURLResponse>(
      {url: `/urls/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: dtosUpdateURLRequest
    },
      options);
    }
  


export const getUpdateURLByIDMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateURLByID>>, TError,{id: string;data: DtosUpdateURLRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateURLByID>>, TError,{id: string;data: DtosUpdateURLRequest}, TContext> => {

const mutationKey = ['updateURLByID'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateURLByID>>, {id: string;data: DtosUpdateURLRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateURLByID(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateURLByIDMutationResult = NonNullable<Awaited<ReturnType<typeof updateURLByID>>>
    export type UpdateURLByIDMutationBody = DtosUpdateURLRequest
    export type UpdateURLByIDMutationError = DtosErrorResponse

    /**
 * @summary Update URL destination
 */
export const useUpdateURLByID = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateURLByID>>, TError,{id: string;data: DtosUpdateURLRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateURLByID>>,
        TError,
        {id: string;data: DtosUpdateURLRequest},
        TContext
      > => {

      const mutationOptions = getUpdateURLByIDMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Retrieve owner-only click analytics for a shortened URL
 * @summary Get URL statistics
 */
export const getURLStatistics = (
    id: string,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<DtosURLStatisticsResponse>(
      {url: `/urls/${id}/statistics`, method: 'GET', signal
    },
      options);
    }
  



export const getGetURLStatisticsQueryKey = (id?: string,) => {
    return [
    `/urls/${id}/statistics`
    ] as const;
    }

    
export const getGetURLStatisticsQueryOptions = <TData = Awaited<ReturnType<typeof getURLStatistics>>, TError = DtosErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLStatistics>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetURLStatisticsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getURLStatistics>>> = ({ signal }) => getURLStatistics(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getURLStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetURLStatisticsQueryResult = NonNullable<Awaited<ReturnType<typeof getURLStatistics>>>
export type GetURLStatisticsQueryError = DtosErrorResponse


export function useGetURLStatistics<TData = Awaited<ReturnType<typeof getURLStatistics>>, TError = DtosErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLStatistics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getURLStatistics>>,
          TError,
          Awaited<ReturnType<typeof getURLStatistics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetURLStatistics<TData = Awaited<ReturnType<typeof getURLStatistics>>, TError = DtosErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLStatistics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getURLStatistics>>,
          TError,
          Awaited<ReturnType<typeof getURLStatistics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetURLStatistics<TData = Awaited<ReturnType<typeof getURLStatistics>>, TError = DtosErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLStatistics>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get URL statistics
 */

export function useGetURLStatistics<TData = Awaited<ReturnType<typeof getURLStatistics>>, TError = DtosErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLStatistics>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetURLStatisticsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Find a shortened URL by its original URL
 * @summary Search URL by original URL
 */
export const postURLsSearch = (
    dtosSearchByOriginalURLRequest: DtosSearchByOriginalURLRequest,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<DomainURL>(
      {url: `/urls/search`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtosSearchByOriginalURLRequest, signal
    },
      options);
    }
  


export const getPostURLsSearchMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postURLsSearch>>, TError,{data: DtosSearchByOriginalURLRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postURLsSearch>>, TError,{data: DtosSearchByOriginalURLRequest}, TContext> => {

const mutationKey = ['postURLsSearch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postURLsSearch>>, {data: DtosSearchByOriginalURLRequest}> = (props) => {
          const {data} = props ?? {};

          return  postURLsSearch(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostURLsSearchMutationResult = NonNullable<Awaited<ReturnType<typeof postURLsSearch>>>
    export type PostURLsSearchMutationBody = DtosSearchByOriginalURLRequest
    export type PostURLsSearchMutationError = DtosErrorResponse

    /**
 * @summary Search URL by original URL
 */
export const usePostURLsSearch = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postURLsSearch>>, TError,{data: DtosSearchByOriginalURLRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postURLsSearch>>,
        TError,
        {data: DtosSearchByOriginalURLRequest},
        TContext
      > => {

      const mutationOptions = getPostURLsSearchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Retrieve a URL by its short code
 * @summary Get URL by short code
 */
export const getURLByShortCode = (
    shortCode: string,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<DomainURL>(
      {url: `/urls/short/${shortCode}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetURLByShortCodeQueryKey = (shortCode?: string,) => {
    return [
    `/urls/short/${shortCode}`
    ] as const;
    }

    
export const getGetURLByShortCodeQueryOptions = <TData = Awaited<ReturnType<typeof getURLByShortCode>>, TError = DtosErrorResponse>(shortCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByShortCode>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetURLByShortCodeQueryKey(shortCode);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getURLByShortCode>>> = ({ signal }) => getURLByShortCode(shortCode, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(shortCode), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getURLByShortCode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetURLByShortCodeQueryResult = NonNullable<Awaited<ReturnType<typeof getURLByShortCode>>>
export type GetURLByShortCodeQueryError = DtosErrorResponse


export function useGetURLByShortCode<TData = Awaited<ReturnType<typeof getURLByShortCode>>, TError = DtosErrorResponse>(
 shortCode: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByShortCode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getURLByShortCode>>,
          TError,
          Awaited<ReturnType<typeof getURLByShortCode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetURLByShortCode<TData = Awaited<ReturnType<typeof getURLByShortCode>>, TError = DtosErrorResponse>(
 shortCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByShortCode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getURLByShortCode>>,
          TError,
          Awaited<ReturnType<typeof getURLByShortCode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetURLByShortCode<TData = Awaited<ReturnType<typeof getURLByShortCode>>, TError = DtosErrorResponse>(
 shortCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByShortCode>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get URL by short code
 */

export function useGetURLByShortCode<TData = Awaited<ReturnType<typeof getURLByShortCode>>, TError = DtosErrorResponse>(
 shortCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getURLByShortCode>>, TError, TData>>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetURLByShortCodeQueryOptions(shortCode,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Resolve a short code and record one click
 * @summary Resolve a short URL
 */
export const resolveShortURL = (
    shortCode: string,
    dtosResolveShortURLRequest: DtosResolveShortURLRequest,
 options?: SecondParameter<typeof authFetch>,signal?: AbortSignal
) => {
      
      
      return authFetch<DtosResolveShortURLResponse>(
      {url: `/urls/short/${shortCode}/resolve`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtosResolveShortURLRequest, signal
    },
      options);
    }
  


export const getResolveShortURLMutationOptions = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resolveShortURL>>, TError,{shortCode: string;data: DtosResolveShortURLRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof resolveShortURL>>, TError,{shortCode: string;data: DtosResolveShortURLRequest}, TContext> => {

const mutationKey = ['resolveShortURL'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resolveShortURL>>, {shortCode: string;data: DtosResolveShortURLRequest}> = (props) => {
          const {shortCode,data} = props ?? {};

          return  resolveShortURL(shortCode,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ResolveShortURLMutationResult = NonNullable<Awaited<ReturnType<typeof resolveShortURL>>>
    export type ResolveShortURLMutationBody = DtosResolveShortURLRequest
    export type ResolveShortURLMutationError = DtosErrorResponse

    /**
 * @summary Resolve a short URL
 */
export const useResolveShortURL = <TError = DtosErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resolveShortURL>>, TError,{shortCode: string;data: DtosResolveShortURLRequest}, TContext>, request?: SecondParameter<typeof authFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resolveShortURL>>,
        TError,
        {shortCode: string;data: DtosResolveShortURLRequest},
        TContext
      > => {

      const mutationOptions = getResolveShortURLMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
