/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * URL Shortener API
 * API for shortening URLs
 * OpenAPI spec version: 1.0
 */

export interface DomainURL {
  created_at?: string;
  id?: string;
  original_url?: string;
  short_code?: string;
  updated_at?: string;
  user_id?: string;
}
