/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * URL Shortener API
 * API for shortening URLs
 * OpenAPI spec version: 1.0
 */
import type { DtosDailyClickResponse } from './dtosDailyClickResponse';
import type { DtosRecentClickResponse } from './dtosRecentClickResponse';
import type { DtosReferrerCountResponse } from './dtosReferrerCountResponse';
import type { DtosURLResponse } from './dtosURLResponse';

export interface DtosURLStatisticsResponse {
  clicks_by_day: DtosDailyClickResponse[];
  last_clicked_at?: string;
  recent_clicks: DtosRecentClickResponse[];
  top_referrers: DtosReferrerCountResponse[];
  total_clicks?: number;
  url: DtosURLResponse;
}
