/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * URL Shortener API
 * API for shortening URLs
 * OpenAPI spec version: 1.0
 */

export interface DtosCreateShortenRequest {
  original_url: string;
}
