/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * URL Shortener API
 * API for shortening URLs
 * OpenAPI spec version: 1.0
 */
import type { DtosTokenResponse } from './dtosTokenResponse';
import type { DtosUserResponse } from './dtosUserResponse';

export interface DtosAuthResponse {
  tokens?: DtosTokenResponse;
  user?: DtosUserResponse;
}
