/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * URL Shortener API
 * API for shortening URLs
 * OpenAPI spec version: 1.0
 */

export interface DtosReferrerCountResponse {
  clicks?: number;
  referrer: string;
}
